#! /usr/bin/env python

# Copyright (c) 2012 Victor Terron. All rights reserved.
# Institute of Astrophysics of Andalusia, IAA-CSIC
#
# This file is part of LEMON.
#
# LEMON is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

import sys

def show_help(name):
    """ Help message, listing all commands, that looks like Git's """

    print "usage: %s COMMAND [ARGS]" % name
    print
    print "The available commands are:"
    print "   import       Group the images of an observing campaign"
    print "   seeing       Identify image with best astronomical seeing"
    print "   offsets      Determine x- and y-offsets of the images"
    print "   mosaic       Combine the images into a master frame"
    print "   astrometry   Calibrate the master frame astrometrically"
    print "   annuli       Find optimal parameters for photometry"
    print "   photometry   Perform aperture photometry"
    print "   diffphot     Generate light curves"
    print "   periods      Dworetsky's string-length method"
    print
    print "See '%s COMMAND' for more information on a specific command." % name

if __name__ == "__main__":

    if len(sys.argv) == 1:
        show_help(sys.argv[0])

